language: julia
julia:
- 1.0
os:
- linux
- osx
notifications:
  email: false
after_success:
- julia -e 'cd(Pkg.dir("BeaData")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
env:
  secure: SPLdmQ2woH32qS7mgoWnGC+fc+nq4xNYCmql/CU//NxkncMpcxa/U0me4PsIG57oVBOQSP3Njbl+EiG5GOLY6ov0+0HRUKvbTX4RlsfeRC28vT6UsB7xFgOz1nM3vMeDPtAiSDN4h9v27E00H5D3kyeZqjMO0xkjEzi1LFiCzMMssndhFsOo8tIUCpyMSQqP/m4KyLB667aJFd8GGq/ee5BGgIQIh6fHjrD2PIV6X7coZjGYn/rzUUcalAkw2gutq5cJOadT2v9KV6olOPDA1BwJ39UBEZ8ohx8Z+IHVCVnh0vqR20O6pIAhQM4ZiZBlkk/x4s5uD004VU9WyXoKGRk6scjjT6uflvmnEgD3oDo1MMlvFTd2QHJao2NxjdHumsFOwZWDHU6/ylGyexuBTkXLvYOKMZv2xAa8+FXUDxKsfQp0RwfXYMK87bqn7rbjx4LZvjuGL2MGuODPoWwaIRrATqNO3CdkAc4n7PxHsf9hluNePZ/3exNXrl4HY60xk5uzmIILYFZF58TldHooWK3KhvN+vOonIJneUHp1PA+qHYSfLSejK+czMuKjvNREeJgnGjR//5ZU5PsqD51YfWO6B4pYLrsF4mTZEWiFYBObygcQI1v4VB/3sbYcY8/Q5M3Xf9JLhEO9YuNE+53DMsoqzYUnEfADixkelUTk8Zk=
